# Generated by Django 3.1.4 on 2020-12-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neelamtenthouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=200)),
            ],
        ),
    ]
