# Generated by Django 3.1.4 on 2020-12-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neelamtenthouse', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
